org.gradle.jvmargs=-Xmx4096m
#启用并行执行任务
# org.gradle.parallel=true
#设置日志级别为info
#org.gradle.logging.level=info
#开启调试日志
#org.gradle.debug=true
kotlin.suppressGradlePluginWarnings=DeprecatedGradleVersionWarning
#android.useDeprecatedNdk=true
#android.databinding.enableV2=true
#android.enableAapt2=true
android.useAndroidX=true
android.injected.testOnly=false
android.enableJetifier=true


