package com.xiajun.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.unit.sp

object MyTextStyles {
    val textPrimary = TextStyle(color = MyColors.TextPrimary)
    val textPrimary11sp = textPrimary.copy(fontSize = 11.sp)
    val textPrimary12sp = textPrimary.copy(fontSize = 12.sp)
    val textPrimary13sp = textPrimary.copy(fontSize = 13.sp)
    val textPrimary14sp = textPrimary.copy(fontSize = 14.sp)
    val textPrimary15sp = textPrimary.copy(fontSize = 15.sp)
    val textPrimary16sp = textPrimary.copy(fontSize = 16.sp)
    val textPrimary17sp = textPrimary.copy(fontSize = 17.sp)
    val textPrimary18sp = textPrimary.copy(fontSize = 18.sp)
    val textSecond = TextStyle(color = MyColors.TextSecond)
    val textSecond11sp = textSecond.copy(fontSize = 11.sp)
    val textSecond12sp = textSecond.copy(fontSize = 12.sp)
    val textSecond13sp = textSecond.copy(fontSize = 13.sp)
    val textSecond14sp = textSecond.copy(fontSize = 14.sp)
    val textSecond15sp = textSecond.copy(fontSize = 15.sp)
    val textSecond16sp = textSecond.copy(fontSize = 16.sp)
    val textSecond17sp = textSecond.copy(fontSize = 17.sp)
    val textSecond18sp = textSecond.copy(fontSize = 18.sp)
    val textGray = TextStyle(color = MyColors.TextGray)
    val textGray11sp = textGray.copy(fontSize = 11.sp)
    val textGray12sp = textGray.copy(fontSize = 12.sp)
    val textGray13sp = textGray.copy(fontSize = 13.sp)
    val textGray14sp = textGray.copy(fontSize = 14.sp)
    val textGray15sp = textGray.copy(fontSize = 15.sp)
    val textGray16sp = textGray.copy(fontSize = 16.sp)
    val textGray17sp = textGray.copy(fontSize = 17.sp)
    val textGray18sp = textGray.copy(fontSize = 18.sp)
    val textGrayLight = TextStyle(color = MyColors.TextGrayLight)
    val textGrayLight11sp = textGrayLight.copy(fontSize = 11.sp)
    val textGrayLight12sp = textGrayLight.copy(fontSize = 12.sp)
    val textGrayLight13sp = textGrayLight.copy(fontSize = 13.sp)
    val textGrayLight14sp = textGrayLight.copy(fontSize = 14.sp)
    val textGrayLight15sp = textGrayLight.copy(fontSize = 15.sp)
    val textGrayLight16sp = textGrayLight.copy(fontSize = 16.sp)
    val textGrayLight17sp = textGrayLight.copy(fontSize = 17.sp)
    val textGrayLight18sp = textGrayLight.copy(fontSize = 18.sp)
    val textWhite = TextStyle(color = Color.White)
    val textWhite11sp = textWhite.copy(fontSize = 11.sp)
    val textWhite12sp = textWhite.copy(fontSize = 12.sp)
    val textWhite13sp = textWhite.copy(fontSize = 13.sp)
    val textWhite14sp = textWhite.copy(fontSize = 14.sp)
    val textWhite15sp = textWhite.copy(fontSize = 15.sp)
    val textWhite16sp = textWhite.copy(fontSize = 16.sp)
    val textWhite17sp = textWhite.copy(fontSize = 17.sp)
    val textWhite18sp = textWhite.copy(fontSize = 18.sp)
}
